import Head from "next/head";
import Header from "@/components/Header";
import FavouriteParagraph from "@/components/FavouriteParagraph";
import Footer from "@/components/Footer";

export default function Favourites() {
  return (
    <>
    <Head>
        <title>GetCooked - Your Favourites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <FavouriteParagraph></FavouriteParagraph>
      <Footer></Footer>
    </>
  );
}